export default {
  BUTTON: 'BUTTON',
  HEADING: 'HEADING',
  TITLE: 'TITLE',
  SUBTITLE: 'SUBTITLE',
  TEXT: 'TEXT',
  IMAGE: 'IMAGE',
  QUICK_REPLIES: 'QUICK_REPLIES',
  TEXT_AND_BUTTONS: 'TEXT_AND_BUTTONS',
  FILE: 'FILE',
  MARKDOWN: 'MARKDOWN'
}
